# Site Settings
#theme: jekyll-theme-slate
title: Jose Fernando Lopez Fernandez
description: The homepage of Jose Fernando Lopez Fernandez
tagline: Software Engineer
email: josefernando.lopezfernandez@proton.me
lang: en
baseurl: "/"
url: "joseflopezfernandez.github.io"
permalink: pretty
markdown: kramdown
highlighter: rouge
sass:
  style: compressed
